/**
 * Shader sources.
 *
 * Two programs. The first evaluates one node's distance field over its own
 * bounding quad and writes a G-buffer; the second reads that G-buffer and
 * does all the lighting at once. That split is the whole reason to be on the
 * GPU: occlusion, shadow, thickness and focus become reads of a field rather
 * than stacked strokes approximating them.
 *
 * There is deliberately no hash function anywhere in here. Float behaviour
 * differs between drivers, so a shader-side noise generator would make output
 * hardware-dependent and the golden images meaningless. Every random value the
 * pipeline uses is generated by the seeded CPU generator and uploaded as a
 * texture.
 */

export const QUAD_VS = `#version 300 es
precision highp float;
layout(location = 0) in vec2 aPos;
uniform vec4 uRect;      // x0, y0, x1, y1 in field units
uniform mat3 uFieldToClip;
out vec2 vField;
void main() {
  vec2 field = mix(uRect.xy, uRect.zw, aPos);
  vField = field;
  vec3 clip = uFieldToClip * vec3(field, 1.0);
  gl_Position = vec4(clip.xy, 0.0, 1.0);
}`

/** A screen-filling triangle. Cheaper than a quad and has no diagonal seam. */
export const FULLSCREEN_VS = `#version 300 es
precision highp float;
out vec2 vUv;
void main() {
  vec2 p = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2);
  vUv = p;
  gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);
}`

/**
 * The field pass.
 *
 * One draw per node. Depth is the distance, so the depth test resolves the
 * union between nodes for free and each pixel keeps the material of whichever
 * form is actually nearest it — which is exactly what a deferred renderer
 * wants and what a painter's-algorithm pass over strokes cannot give.
 */
export const FIELD_FS = `#version 300 es
precision highp float;

#define MAX_LEAVES 8

in vec2 vField;

uniform vec4 uLeafA[MAX_LEAVES];
uniform vec4 uLeafB[MAX_LEAVES];
uniform int  uKind[MAX_LEAVES];
uniform int  uOp[MAX_LEAVES];
uniform int  uCount;
uniform float uSmoothK;
uniform vec4 uCutA[MAX_LEAVES];
uniform vec4 uCutB[MAX_LEAVES];
uniform int  uCutKind[MAX_LEAVES];
uniform int  uCutOp[MAX_LEAVES];
uniform int  uCutCount;

uniform vec3  uAlbedo;
uniform float uMaterial;
uniform float uPlane;
uniform float uEmissive;
uniform float uUnit;     // design units to pixels
uniform float uBevel;    // edge bevel width, design units
uniform float uDepthRange;

layout(location = 0) out vec4 oAlbedo;   // rgb albedo, a material id
layout(location = 1) out vec4 oSurface;  // xy normal, z plane, w thickness
layout(location = 2) out vec4 oField;    // x distance, y emissive

float sdBox(vec2 p, vec2 c, vec2 b, float r) {
  vec2 q = abs(p - c) - b + r;
  return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;
}

/**
 * Ellipse distance, approximated.
 *
 * The exact signed distance to an ellipse needs a quartic root and is far more
 * expensive than everything else in this shader put together. Scaling to the
 * unit circle and rescaling by the smaller radius gives the correct zero set
 * and a conservative under-estimate everywhere else, which is precisely what
 * the marchers downstream need: an under-estimate makes a shadow march take
 * more, smaller steps, so it stays correct and only costs a little.
 */
float sdEllipse(vec2 p, vec2 c, vec2 ab) {
  vec2 q = (p - c) / ab;
  return (length(q) - 1.0) * min(ab.x, ab.y);
}

float sdCapsule(vec2 p, vec2 a, vec2 b, float r) {
  vec2 pa = p - a;
  vec2 ba = b - a;
  float h = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-6), 0.0, 1.0);
  return length(pa - ba * h) - r;
}

float leafOf(vec4 a, vec4 b, int k, vec2 p) {
  if (k == 0) return sdBox(p, a.xy, a.zw, b.x);
  if (k == 1) return sdEllipse(p, a.xy, a.zw);
  return sdCapsule(p, a.xy, a.zw, b.x);
}

float leafAt(int i, vec2 p) { return leafOf(uLeafA[i], uLeafB[i], uKind[i], p); }
float cutAt(int i, vec2 p) { return leafOf(uCutA[i], uCutB[i], uCutKind[i], p); }

float opSmooth(float a, float b, float k) {
  float h = clamp(0.5 + 0.5 * (b - a) / max(k, 1e-4), 0.0, 1.0);
  return mix(b, a, h) - k * h * (1.0 - h);
}

float combine(float d, float e, int op) {
  if (op == 0) return min(d, e);
  if (op == 1) return opSmooth(d, e, uSmoothK);
  if (op == 2) return max(d, -e);
  return max(d, e);
}

float fieldAt(vec2 p) {
  float d = leafAt(0, p);
  for (int i = 1; i < MAX_LEAVES; i++) {
    if (i >= uCount) break;
    d = combine(d, leafAt(i, p), uOp[i]);
  }
  // The cut is folded on its own and removed as one shape. Folding it into the
  // line above instead would subtract each of its parts separately, which is a
  // different and wrong shape.
  if (uCutCount > 0) {
    float c = cutAt(0, p);
    for (int i = 1; i < MAX_LEAVES; i++) {
      if (i >= uCutCount) break;
      c = combine(c, cutAt(i, p), uCutOp[i]);
    }
    d = max(d, -c);
  }
  return d;
}

void main() {
  float d = fieldAt(vField);

  // Analytic antialiasing: the coverage of a pixel by a half-plane at distance
  // d is a smoothstep across one pixel. Exact at any resolution, which is why
  // the export needs no supersampling to be clean.
  float px = 1.0 / max(uUnit, 1e-6);
  float cover = 1.0 - smoothstep(-px, px, d);
  if (cover < 0.004) discard;

  // The gradient of a distance field IS the surface normal, so it costs two
  // extra evaluations rather than a normal map.
  float e = px * 1.5;
  vec2 grad = normalize(vec2(
    fieldAt(vField + vec2(e, 0.0)) - fieldAt(vField - vec2(e, 0.0)),
    fieldAt(vField + vec2(0.0, e)) - fieldAt(vField - vec2(0.0, e))
  ) + 1e-6);

  // Bevel the edge into the third dimension: flat in the middle of a form,
  // turning over within uBevel of its outline. This is what lets a flat shape
  // take a real specular without anyone authoring a normal.
  float nz = clamp(-d / max(uBevel, 1e-4), 0.0, 1.0);
  vec2 nxy = grad * sqrt(max(0.0, 1.0 - nz * nz));

  /**
   * Depth is the PLANE, with distance only as a tiebreak.
   *
   * Encoding distance alone looks right and is not: the scale was the node's
   * own bevel, so an arch and a coursing line on top of it were being compared
   * in different units. A hairline a pixel inside its own outline reported a
   * depth near the middle of the range while the arch beneath it, twenty units
   * deep, reported a much smaller one — so the arch won pixels belonging to the
   * line, and the parts of the line that did win were the ones just outside the
   * arch. That is what put a fringe of ticks around every form.
   *
   * Plane is already the depth of the node and is the same quantity for every
   * node in the frame, so it takes the high bits and distance breaks ties
   * within a plane.
   */
  gl_FragDepth = clamp(
    (1.0 - uPlane) * 0.97 + 0.03 * clamp(0.5 + d / uDepthRange, 0.0, 1.0),
    0.0, 1.0
  );

  oAlbedo = vec4(uAlbedo, uMaterial);
  oSurface = vec4(nxy, uPlane, clamp(-d, 0.0, 1e4));
  oField = vec4(d, uEmissive, cover, 1.0);
}`

/**
 * The deferred pass.
 *
 * Everything the CPU pipeline approximated with stacked passes, done as reads
 * of the distance field: occlusion by sampling it on a disc, shadow by cone
 * marching it toward the light, subsurface warmth from the thickness it
 * already carries, and depth of field from a circle of confusion rather than
 * discrete tiers.
 */
export const LIGHT_FS = `#version 300 es
precision highp float;

in vec2 vUv;
out vec4 oColor;

uniform sampler2D uAlbedo;
uniform sampler2D uSurface;
uniform sampler2D uField;
uniform sampler2D uNoise;

uniform vec2  uRes;
uniform vec2  uLight;      // 2D direction toward the light
uniform vec3  uGround;
uniform vec3  uInk;
uniform vec3  uAccent;
uniform float uUnit;
uniform float uAo;
uniform float uShadow;
uniform float uSss;
uniform float uFocus;      // focus plane, 0..1
uniform float uDofStrength;
uniform vec2  uFocusUv;
uniform vec3  uSkyTop;
uniform vec3  uSkyGlow;
uniform float uAmbient;
uniform float uDirect;

float fieldAt(vec2 uv) { return texture(uField, uv).x; }

/**
 * Ambient occlusion, from the plane buffer rather than from an in-plane march.
 *
 * The obvious thing — march the distance field along the surface normal, the
 * standard SDF occlusion — is wrong here, and wrong in a way worth recording.
 * That technique assumes you start on a surface and march away from it through
 * empty space. This scene is a face-on relief: the "surface" of a form is its
 * whole interior, a flat plate pointing at the viewer, and marching in-plane
 * from an interior point immediately runs through more of the same solid. The
 * field reports large negative distances, the march reads that as total
 * enclosure, and every filled pixel comes out black.
 *
 * What actually occludes a plate is a NEARER plate beside it. So the ring
 * samples ask the plane buffer, not the field: a covered neighbour closer to
 * the viewer casts, and the form's own outline contributes a short edge
 * darkening, which is the cue that reads as solidity.
 */
float occlusion(vec2 uv, float myPlane, float d, float band) {
  float occ = 0.0;
  for (int i = 0; i < 8; i++) {
    float a = float(i) * 0.7853981634 + 0.4;
    vec2 off = vec2(cos(a), sin(a)) * (0.008 + 0.014 * float(i & 3));
    vec4 sn = texture(uSurface, uv + off);
    float sd = texture(uField, uv + off).x;
    occ += step(sd, 0.0) * step(myPlane + 0.02, sn.z);
  }
  occ /= 8.0;
  float edge = 1.0 - smoothstep(0.0, band, -d);
  return clamp(1.0 - occ * 0.7 - edge * 0.28, 0.0, 1.0);
}

/**
 * Soft shadow, marched over the same buffer.
 *
 * Weighting each hit by the reciprocal of how far along the ray it was found is
 * what produces the penumbra: a caster close to the receiver is sampled early,
 * where the weight is near one, and takes a crisp edge; a distant caster is
 * sampled late among many low weights and smears out. Nothing about softness is
 * authored, and no caster ever shadows itself because the test requires the
 * occluder to be on a nearer plane than the receiver.
 */
float shadow(vec2 uv, float myPlane) {
  float occ = 0.0;
  float w = 0.0;
  for (int i = 1; i <= 20; i++) {
    float t = float(i) * 0.013;
    vec2 p = uv + uLight * t;
    if (p.x < 0.0 || p.y < 0.0 || p.x > 1.0 || p.y > 1.0) break;
    float sp = texture(uSurface, p).z;
    float sd = texture(uField, p).x;
    float wt = 1.0 / (1.0 + t * 8.0);
    occ += step(sd, 0.0) * step(myPlane + 0.02, sp) * wt;
    w += wt;
  }
  return clamp(1.0 - 1.5 * occ / max(w, 1e-4), 0.0, 1.0);
}

void main() {
  vec4 alb = texture(uAlbedo, vUv);
  vec4 srf = texture(uSurface, vUv);
  vec4 fld = texture(uField, vUv);

  float cover = fld.z;
  float unit = uUnit;

  /**
   * The sky: a two-pole gradient standing in for the blurred colour fields the
   * CPU path built out of five ellipses. It is both cheaper and better — a
   * gradient evaluated per pixel has no banding to hide and no shapes to
   * accidentally see the edges of.
   */
  vec2 d2 = vUv - uFocusUv;
  d2.x *= uRes.x / uRes.y;
  float glow = 1.0 - smoothstep(0.0, 0.85, length(d2));
  vec3 col = mix(uGround, uSkyTop, smoothstep(1.0, 0.0, vUv.y) * 0.85);
  col = mix(col, uSkyGlow, glow * 0.32);

  if (cover > 0.004) {
    vec3 n = vec3(srf.xy, sqrt(max(0.0, 1.0 - dot(srf.xy, srf.xy))));
    vec3 l = normalize(vec3(uLight, 0.85));

    float band = 34.0 / max(uRes.y / max(unit, 1e-4), 1e-4);
    float ao = mix(1.0, occlusion(vUv, srf.z, fld.x, band * 240.0), uAo);
    float sh = mix(1.0, shadow(vUv, srf.z), uShadow);
    float diff = clamp(dot(n, l), 0.0, 1.0);

    // Subsurface: thin parts of a form pass light. Reading thickness straight
    // off the field is what makes an edge warm without anyone painting it.
    float thick = srf.w / max(unit * 40.0, 1e-4);
    float sss = exp(-thick * 3.0) * uSss;

    /**
     * Ambient is occluded but never shadowed, and direct is shadowed but never
     * occluded. Multiplying one term by both is what drove the whole frame to
     * near-black: a surface in shadow with a little occlusion on it was being
     * scaled twice for the same reason, and nothing in the picture had a floor.
     */
    vec3 ambient = alb.rgb * uAmbient * ao;
    vec3 direct = alb.rgb * diff * sh * uDirect;
    vec3 lit = ambient + direct;
    lit += uAccent * sss * 0.3;
    // An emissive form is bright because the bloom says so, not because its
    // own body is. Pushed hard here as well it arrives at the composite
    // already past one and clips flat, losing the shape inside the light.
    lit = mix(lit, lit * 0.8 + uAccent * 0.4, fld.y);

    col = mix(col, lit, cover);
  }

  // A little dither before the 8-bit write, because the largest areas of this
  // image are smooth falloffs and that is exactly where banding shows.
  vec3 noise = texture(uNoise, vUv * (uRes / 256.0)).rgb - 0.5;
  col += noise * (1.5 / 255.0);

  oColor = vec4(col, 1.0);
}`

/**
 * Depth of field, as a gather.
 *
 * A real circle of confusion: each pixel's blur radius comes from how far its
 * plane is from focus, and the gather samples a disc of that radius. The CPU
 * pipeline had to quantise this into three tiers because it was compositing
 * whole buffers; here it is per pixel and continuous, and the near/far
 * asymmetry a lens actually has comes with it.
 */
export const DOF_FS = `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 oColor;
uniform sampler2D uColor;
uniform sampler2D uSurface;
uniform vec2 uRes;
uniform float uFocus;
uniform float uStrength;
uniform float uBand;

void main() {
  float plane = texture(uSurface, vUv).z;
  /**
   * A depth OF FIELD, not a focus plane.
   *
   * Blurring in proportion to distance from a single plane means only one
   * depth in the frame is ever sharp, and everything else is on a ramp away
   * from it — which is why the whole mid-ground was going soft. A real lens
   * has a band that is acceptably sharp and only departs from it beyond that,
   * so the circle of confusion starts at zero and stays there across uBand.
   */
  float coc = max(0.0, abs(plane - uFocus) - uBand) * uStrength;
  // a near-field blur is wider than a far-field one at the same distance
  coc *= plane > uFocus ? 1.35 : 1.0;
  float r = coc * uRes.y * 0.02;
  if (r < 0.75) { oColor = texture(uColor, vUv); return; }

  vec3 sum = vec3(0.0);
  float w = 0.0;
  for (int i = 0; i < 16; i++) {
    float a = float(i) * 2.39996;          // golden angle, so the disc fills evenly
    float rad = sqrt(float(i) / 16.0) * r;
    vec2 off = vec2(cos(a), sin(a)) * rad / uRes;
    vec3 s = texture(uColor, vUv + off).rgb;
    // weight by how much that sample belongs at this depth, so a sharp
    // foreground does not smear into a blurred background
    float sp = texture(uSurface, vUv + off).z;
    float ww = 1.0 - clamp(abs(sp - plane) * 2.5, 0.0, 0.9);
    sum += s * ww;
    w += ww;
  }
  oColor = vec4(sum / max(w, 1e-4), 1.0);
}`

/** Bright-pass, for the bloom mip chain. */
export const BRIGHT_FS = `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 oColor;
uniform sampler2D uColor;
uniform sampler2D uField;
uniform float uThreshold;
void main() {
  vec3 c = texture(uColor, vUv).rgb;
  float e = texture(uField, vUv).y;
  float lum = dot(c, vec3(0.2126, 0.7152, 0.0722));
  float k = max(0.0, lum - uThreshold) / max(1.0 - uThreshold, 1e-4);
  oColor = vec4(c * max(k, e * 0.9), 1.0);
}`

/** Separable Gaussian, run down the mip chain. */
export const BLUR_FS = `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 oColor;
uniform sampler2D uColor;
uniform vec2 uDir;
void main() {
  vec3 s = texture(uColor, vUv).rgb * 0.227027;
  s += texture(uColor, vUv + uDir * 1.3846).rgb * 0.316216;
  s += texture(uColor, vUv - uDir * 1.3846).rgb * 0.316216;
  s += texture(uColor, vUv + uDir * 3.2307).rgb * 0.070270;
  s += texture(uColor, vUv - uDir * 3.2307).rgb * 0.070270;
  oColor = vec4(s, 1.0);
}`

/**
 * Composite, grade and film.
 *
 * Halation is a second, wider tap of the same bloom chain pushed toward red,
 * because film scatters a hot highlight furthest in its red layer. That is why
 * the halo around a bright edge is warm even when the light making it is not.
 */
export const COMPOSITE_FS = `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 oColor;

uniform sampler2D uColor;
uniform sampler2D uBloom;
uniform sampler2D uWide;
uniform sampler2D uNoise;
uniform vec2 uRes;
uniform vec2 uVigCentre;
uniform float uVignette;
uniform float uGrain;
uniform float uBloomAmt;
uniform float uWarmth;

void main() {
  vec3 col = texture(uColor, vUv).rgb;
  col += texture(uBloom, vUv).rgb * uBloomAmt;
  vec3 halo = texture(uWide, vUv).rgb;
  col += halo * vec3(1.0, 0.62, 0.42) * uBloomAmt * 0.55;

  // split tone: shadows cool, highlights warm
  float lum = dot(col, vec3(0.2126, 0.7152, 0.0722));
  col += vec3(-0.012, -0.004, 0.026) * (1.0 - smoothstep(0.0, 0.45, lum));
  col += vec3(0.028, 0.012, -0.014) * smoothstep(0.5, 1.0, lum) * (1.0 + uWarmth);

  /**
   * A shoulder before anything else.
   *
   * The toe alone sets a floor but does nothing about the top: bloom adds
   * energy, so an emissive form arrives here well past one and the write to an
   * 8-bit target simply clips it, flattening the inside of every light in the
   * frame to a single value. Compressing above a knee, asymptotic to one,
   * keeps the shape in the highlight and guarantees nothing reaches pure white.
   */
  float knee = 0.72;
  vec3 over = max(col - knee, 0.0);
  col = min(col, vec3(knee)) + (1.0 - knee) * (1.0 - exp(-over / (1.0 - knee)));

  // anisotropic vignette: on a 9:16 frame a symmetric one eats the short edges
  vec2 d = (vUv - uVigCentre);
  d.x *= max(uRes.x / uRes.y, 1.0);
  d.y *= max(uRes.y / uRes.x, 1.0);
  float v = 1.0 - uVignette * 0.3 * pow(clamp(dot(d, d) * 1.15, 0.0, 1.0), 2.0);
  col *= v;

  // Compress the last two percent at each end, AFTER the vignette. Doing it
  // before means the vignette immediately puts the corners back under the
  // floor that the compression exists to establish, which is how a frame ends
  // up clipping at black in exactly the places the toe was meant to protect.
  col = 0.025 + col * (1.0 - 0.025 - 0.022);

  vec3 grain = texture(uNoise, vUv * (uRes / 256.0)).rgb - 0.5;
  col += grain * uGrain;

  oColor = vec4(col, 1.0);
}`
